// ─── Ghana Regions & Districts ───────────────────────────────────────────────
// 16 Regions · 276 Districts
// Source: Ghana Statistical Service 2019 district structure

export interface District {
  name: string;
  capital: string;
}

export interface Region {
  name: string;
  capital: string;
  code: string;
  districts: District[];
}

export const GHANA_REGIONS: Region[] = [
  {
    name: 'Greater Accra',
    capital: 'Accra',
    code: 'GAR',
    districts: [
      { name: 'Accra Metropolitan', capital: 'Accra' },
      { name: 'Tema Metropolitan', capital: 'Tema' },
      { name: 'Adentan Municipal', capital: 'Adentan' },
      { name: 'Ashaiman Municipal', capital: 'Ashaiman' },
      { name: 'Ayawaso Central Municipal', capital: 'Accra' },
      { name: 'Ayawaso East Municipal', capital: 'Accra' },
      { name: 'Ayawaso North Municipal', capital: 'Accra' },
      { name: 'Ayawaso West Municipal', capital: 'Accra' },
      { name: 'Ga Central Municipal', capital: 'Sowutuom' },
      { name: 'Ga East Municipal', capital: 'Abokobi' },
      { name: 'Ga North Municipal', capital: 'Ofankor' },
      { name: 'Ga South Municipal', capital: 'Weija' },
      { name: 'Ga West Municipal', capital: 'Amasaman' },
      { name: 'Kpone-Katamanso Municipal', capital: 'Kpone' },
      { name: 'Krowor Municipal', capital: 'Teshie' },
      { name: 'La Dade-Kotopon Municipal', capital: 'La' },
      { name: 'La Nkwantanang-Madina Municipal', capital: 'Madina' },
      { name: 'Ledzokuku Municipal', capital: 'Teshie' },
      { name: 'Ningo-Prampram District', capital: 'Prampram' },
      { name: 'Okaikwei North Municipal', capital: 'Accra' },
      { name: 'Shai-Osudoku District', capital: 'Dodowa' },
      { name: 'Tema West Municipal', capital: 'Tema' },
      { name: 'Weija-Gbawe Municipal', capital: 'Weija' },
    ],
  },
  {
    name: 'Ashanti',
    capital: 'Kumasi',
    code: 'ASH',
    districts: [
      { name: 'Kumasi Metropolitan', capital: 'Kumasi' },
      { name: 'Obuasi Municipal', capital: 'Obuasi' },
      { name: 'Adansi Asokwa District', capital: 'Adansi Asokwa' },
      { name: 'Adansi North District', capital: 'New Edubiase' },
      { name: 'Afigya-Kwabre South District', capital: 'Afrancho' },
      { name: 'Ahafo Ano North Municipal', capital: 'Tepa' },
      { name: 'Ahafo Ano South East District', capital: 'Mankranso' },
      { name: 'Ahafo Ano South West District', capital: 'Kumawu' },
      { name: 'Amansie Central District', capital: 'Jacobu' },
      { name: 'Amansie South District', capital: 'Manso Nkwanta' },
      { name: 'Amansie West District', capital: 'Manso Amenfi' },
      { name: 'Asante Akim Central Municipal', capital: 'Konongo' },
      { name: 'Asante Akim North District', capital: 'Agogo' },
      { name: 'Asante Akim South District', capital: 'Juaso' },
      { name: 'Asokore Mampong Municipal', capital: 'Asokore Mampong' },
      { name: 'Asokwa Municipal', capital: 'Asokwa' },
      { name: 'Atwima Kwanwoma District', capital: 'Foase' },
      { name: 'Atwima Mponua District', capital: 'Nyinahin' },
      { name: 'Atwima Nwabiagya Municipal', capital: 'Barekese' },
      { name: 'Atwima Nwabiagya North District', capital: 'Abuakwa' },
      { name: 'Bekwai Municipal', capital: 'Bekwai' },
      { name: 'Bosome Freho District', capital: 'Asiwa' },
      { name: 'Bosomtwe District', capital: 'Kuntanase' },
      { name: 'Ejisu Municipal', capital: 'Ejisu' },
      { name: 'Ejura-Sekyedumase Municipal', capital: 'Ejura' },
      { name: 'Juaben Municipal', capital: 'Juaben' },
      { name: 'Kwabre East Municipal', capital: 'Mamponteng' },
      { name: 'Kwadaso Municipal', capital: 'Kwadaso' },
      { name: 'Mampong Municipal', capital: 'Mampong' },
      { name: 'Obuasi East District', capital: 'Obuasi East' },
      { name: 'Offinso Municipal', capital: 'Offinso' },
      { name: 'Offinso North District', capital: 'Afrancho' },
      { name: 'Oforikrom Municipal', capital: 'Oforikrom' },
      { name: 'Old Tafo Municipal', capital: 'Old Tafo' },
      { name: 'Sekyere Afram Plains District', capital: 'Drobonso' },
      { name: 'Sekyere Kumawu District', capital: 'Kumawu' },
      { name: 'Sekyere Central District', capital: 'Agona' },
      { name: 'Sekyere East District', capital: 'Effiduase' },
      { name: 'Sekyere South District', capital: 'Nsuta' },
      { name: 'Suame Municipal', capital: 'Suame' },
      { name: 'Tafo-Pankrono Municipal', capital: 'Tafo' },
    ],
  },
  {
    name: 'Western',
    capital: 'Sekondi-Takoradi',
    code: 'WES',
    districts: [
      { name: 'Sekondi-Takoradi Metropolitan', capital: 'Sekondi' },
      { name: 'Ahanta West Municipal', capital: 'Agona Nkwanta' },
      { name: 'Amenfi Central District', capital: 'Manso Amenfi' },
      { name: 'Amenfi East District', capital: 'Wassa Akropong' },
      { name: 'Amenfi West District', capital: 'Asankrangwa' },
      { name: 'Effia-Kwesimintsim Municipal', capital: 'Kwesimintsim' },
      { name: 'Ellembelle District', capital: 'Nkroful' },
      { name: 'Jomoro Municipal', capital: 'Half Assini' },
      { name: 'Mpohor District', capital: 'Mpohor' },
      { name: 'Nzema East Municipal', capital: 'Axim' },
      { name: 'Prestea-Huni Valley Municipal', capital: 'Prestea' },
      { name: 'Shama District', capital: 'Shama' },
      { name: 'Tarkwa-Nsuaem Municipal', capital: 'Tarkwa' },
      { name: 'Wassa Amenfi Municipal', capital: 'Wassa Akropong' },
      { name: 'Wassa East District', capital: 'Daboase' },
    ],
  },
  {
    name: 'Western North',
    capital: 'Sefwi Wiawso',
    code: 'WNR',
    districts: [
      { name: 'Aowin Municipal', capital: 'Enchi' },
      { name: 'Bia East District', capital: 'Debiso' },
      { name: 'Bia West District', capital: 'Sefwi Bekwai' },
      { name: 'Bibiani-Anhwiaso-Bekwai Municipal', capital: 'Bibiani' },
      { name: 'Bodi District', capital: 'Bodi' },
      { name: 'Juaboso District', capital: 'Juaboso' },
      { name: 'Sefwi Akontombra District', capital: 'Akontombra' },
      { name: 'Sefwi Wiawso Municipal', capital: 'Sefwi Wiawso' },
      { name: 'Suaman District', capital: 'Dadieso' },
    ],
  },
  {
    name: 'Central',
    capital: 'Cape Coast',
    code: 'CEN',
    districts: [
      { name: 'Cape Coast Metropolitan', capital: 'Cape Coast' },
      { name: 'Abura-Asebu-Kwamankese District', capital: 'Abura Dunkwa' },
      { name: 'Agona East District', capital: 'Agona Duakwa' },
      { name: 'Agona West Municipal', capital: 'Agona Swedru' },
      { name: 'Ajumako-Enyan-Essiam District', capital: 'Ajumako' },
      { name: 'Asikuma-Odoben-Brakwa District', capital: 'Breman Asikuma' },
      { name: 'Assin Central Municipal', capital: 'Assin Fosu' },
      { name: 'Assin North District', capital: 'Assin Bereku' },
      { name: 'Assin South District', capital: 'Assin Praso' },
      { name: 'Awutu Senya District', capital: 'Swedru' },
      { name: 'Awutu Senya East Municipal', capital: 'Kasoa' },
      { name: 'Efutu Municipal', capital: 'Winneba' },
      { name: 'Ekumfi District', capital: 'Ekumfi Otuam' },
      { name: 'Gomoa Central District', capital: 'Apam' },
      { name: 'Gomoa East District', capital: 'Afransi' },
      { name: 'Gomoa West District', capital: 'Apam' },
      { name: 'Hemang-Lower Denkyira District', capital: 'Diaso' },
      { name: 'Komenda-Edina-Eguafo-Abirem Municipal', capital: 'Komenda' },
      { name: 'Mfantsiman Municipal', capital: 'Saltpond' },
      { name: 'Twifo Atti-Morkwa District', capital: 'Twifo Praso' },
      { name: 'Twifo Hemang Lower Denkyira District', capital: 'Twifo Praso' },
      { name: 'Upper Denkyira East Municipal', capital: 'Dunkwa-on-Offin' },
      { name: 'Upper Denkyira West District', capital: 'Ewoyaa' },
    ],
  },
  {
    name: 'Eastern',
    capital: 'Koforidua',
    code: 'EAS',
    districts: [
      { name: 'New Juaben South Municipal', capital: 'Koforidua' },
      { name: 'New Juaben North Municipal', capital: 'Effiduase' },
      { name: 'Abuakwa North Municipal', capital: 'Kukurantumi' },
      { name: 'Abuakwa South Municipal', capital: 'Kukurantumi' },
      { name: 'Achiase District', capital: 'Achiase' },
      { name: 'Akuapem North Municipal', capital: 'Akropong' },
      { name: 'Akuapem South District', capital: 'Aburi' },
      { name: 'Akyemansa District', capital: 'Ofoase' },
      { name: 'Asene-Manso-Akroso District', capital: 'Asene' },
      { name: 'Atiwa East District', capital: 'Kwabeng' },
      { name: 'Atiwa West District', capital: 'Atiwa' },
      { name: 'Ayensuano District', capital: 'Coaltar' },
      { name: 'Birim Central Municipal', capital: 'Akim Oda' },
      { name: 'Birim North District', capital: 'Akim Swedru' },
      { name: 'Birim South District', capital: 'Akim Asafo' },
      { name: 'Denkyembuor District', capital: 'Kwaebibirem' },
      { name: 'Fanteakwa North District', capital: 'Begoro' },
      { name: 'Fanteakwa South District', capital: 'Osino' },
      { name: 'Kwaebibirem Municipal', capital: 'Kade' },
      { name: 'Kwahu Afram Plains North District', capital: 'Donkorkrom' },
      { name: 'Kwahu Afram Plains South District', capital: 'Tease' },
      { name: 'Kwahu East District', capital: 'Abetifi' },
      { name: 'Kwahu South District', capital: 'Mpraeso' },
      { name: 'Kwahu West Municipal', capital: 'Nkawkaw' },
      { name: 'Lower Manya Krobo Municipal', capital: 'Odumase Krobo' },
      { name: 'Nsawam-Adoagyiri Municipal', capital: 'Nsawam' },
      { name: 'Okere District', capital: 'Okere' },
      { name: 'Suhum Municipal', capital: 'Suhum' },
      { name: 'Upper Manya Krobo District', capital: 'Asesewa' },
      { name: 'Upper West Akim District', capital: 'Adeiso' },
      { name: 'West Akim Municipal', capital: 'Asamankese' },
      { name: 'Yilo Krobo Municipal', capital: 'Somanya' },
    ],
  },
  {
    name: 'Volta',
    capital: 'Ho',
    code: 'VOL',
    districts: [
      { name: 'Ho Municipal', capital: 'Ho' },
      { name: 'Adaklu District', capital: 'Adaklu Waya' },
      { name: 'Afadjato South District', capital: 'Hohoe' },
      { name: 'Agotime-Ziope District', capital: 'Kpetoe' },
      { name: 'Akatsi North District', capital: 'Dzodze' },
      { name: 'Akatsi South District', capital: 'Akatsi' },
      { name: 'Anloga District', capital: 'Anloga' },
      { name: 'Central Tongu District', capital: 'Adidome' },
      { name: 'Ho West District', capital: 'Kpeve' },
      { name: 'Hohoe Municipal', capital: 'Hohoe' },
      { name: 'Keta Municipal', capital: 'Keta' },
      { name: 'Ketu North Municipal', capital: 'Dzodze' },
      { name: 'Ketu South Municipal', capital: 'Denu' },
      { name: 'Kpando Municipal', capital: 'Kpando' },
      { name: 'North Dayi District', capital: 'Anfoega' },
      { name: 'North Tongu District', capital: 'Battor' },
      { name: 'Nkwanta North District', capital: 'Kpassa' },
      { name: 'Nkwanta South Municipal', capital: 'Nkwanta' },
      { name: 'South Dayi District', capital: 'Peki' },
      { name: 'South Tongu District', capital: 'Sogakope' },
    ],
  },
  {
    name: 'Oti',
    capital: 'Dambai',
    code: 'OTI',
    districts: [
      { name: 'Biakoye District', capital: 'Nkonya Ahenkro' },
      { name: 'Jasikan District', capital: 'Jasikan' },
      { name: 'Kadjebi District', capital: 'Kadjebi' },
      { name: 'Krachi East Municipal', capital: 'Dambai' },
      { name: 'Krachi Nchumuru District', capital: 'Chinderi' },
      { name: 'Krachi West District', capital: 'Kete Krachi' },
      { name: 'Nkwanta North District', capital: 'Kpassa' },
      { name: 'Nkwanta South Municipal', capital: 'Nkwanta' },
    ],
  },
  {
    name: 'Bono',
    capital: 'Sunyani',
    code: 'BON',
    districts: [
      { name: 'Sunyani Municipal', capital: 'Sunyani' },
      { name: 'Berekum East Municipal', capital: 'Berekum' },
      { name: 'Berekum West District', capital: 'Jinijini' },
      { name: 'Banda District', capital: 'Banda Ahenkro' },
      { name: 'Dormaa Central Municipal', capital: 'Dormaa Ahenkro' },
      { name: 'Dormaa East District', capital: 'Wamfie' },
      { name: 'Dormaa West District', capital: 'Dromankese' },
      { name: 'Jaman North Municipal', capital: 'Drobo' },
      { name: 'Jaman South Municipal', capital: 'Sampa' },
      { name: 'Sunyani West District', capital: 'Odumasi' },
      { name: 'Tain District', capital: 'Nsawkaw' },
      { name: 'Wenchi Municipal', capital: 'Wenchi' },
    ],
  },
  {
    name: 'Bono East',
    capital: 'Techiman',
    code: 'BNE',
    districts: [
      { name: 'Techiman Municipal', capital: 'Techiman' },
      { name: 'Techiman North District', capital: 'Tuobodom' },
      { name: 'Atebubu-Amantin Municipal', capital: 'Atebubu' },
      { name: 'Kintampo North Municipal', capital: 'Kintampo' },
      { name: 'Kintampo South District', capital: 'Jema' },
      { name: 'Nkoranza North District', capital: 'Busunya' },
      { name: 'Nkoranza South Municipal', capital: 'Nkoranza' },
      { name: 'Pru East District', capital: 'Yeji' },
      { name: 'Pru West District', capital: 'Prang' },
      { name: 'Sene East District', capital: 'Kajaji' },
      { name: 'Sene West District', capital: 'Kwame Danso' },
    ],
  },
  {
    name: 'Ahafo',
    capital: 'Goaso',
    code: 'AHA',
    districts: [
      { name: 'Asunafo North Municipal', capital: 'Goaso' },
      { name: 'Asunafo South District', capital: 'Kukuom' },
      { name: 'Asutifi North District', capital: 'Kenyasi' },
      { name: 'Asutifi South District', capital: 'Hwidiem' },
      { name: 'Tano North Municipal', capital: 'Duayaw Nkwanta' },
      { name: 'Tano South Municipal', capital: 'Bechem' },
    ],
  },
  {
    name: 'Northern',
    capital: 'Tamale',
    code: 'NOR',
    districts: [
      { name: 'Tamale Metropolitan', capital: 'Tamale' },
      { name: 'Gushegu Municipal', capital: 'Gushegu' },
      { name: 'Karaga District', capital: 'Karaga' },
      { name: 'Kpandai District', capital: 'Kpandai' },
      { name: 'Kumbungu District', capital: 'Kumbungu' },
      { name: 'Mion District', capital: 'Sang' },
      { name: 'Nanton District', capital: 'Nanton' },
      { name: 'Nanumba North Municipal', capital: 'Bimbilla' },
      { name: 'Nanumba South District', capital: 'Wulensi' },
      { name: 'Saboba District', capital: 'Saboba' },
      { name: 'Sagnarigu Municipal', capital: 'Sagnarigu' },
      { name: 'Savelugu Municipal', capital: 'Savelugu' },
      { name: 'Tatale-Sanguli District', capital: 'Tatale' },
      { name: 'Tolon District', capital: 'Tolon' },
      { name: 'Yendi Municipal', capital: 'Yendi' },
      { name: 'Zabzugu District', capital: 'Zabzugu' },
    ],
  },
  {
    name: 'Savannah',
    capital: 'Damongo',
    code: 'SAV',
    districts: [
      { name: 'Bole District', capital: 'Bole' },
      { name: 'Central Gonja District', capital: 'Buipe' },
      { name: 'East Gonja Municipal', capital: 'Salaga' },
      { name: 'North East Gonja District', capital: 'Daboya' },
      { name: 'North Gonja District', capital: 'Damongo' },
      { name: 'Sawla-Tuna-Kalba District', capital: 'Sawla' },
      { name: 'West Gonja Municipal', capital: 'Damongo' },
    ],
  },
  {
    name: 'North East',
    capital: 'Nalerigu',
    code: 'NER',
    districts: [
      { name: 'Bunkpurugu-Nakpayili District', capital: 'Bunkpurugu' },
      { name: 'Chereponi District', capital: 'Chereponi' },
      { name: 'East Mamprusi Municipal', capital: 'Gambaga' },
      { name: 'Mamprugu-Moagduri District', capital: 'Yagaba' },
      { name: 'West Mamprusi Municipal', capital: 'Walewale' },
      { name: 'Yunyoo-Nasuan District', capital: 'Yunyoo' },
    ],
  },
  {
    name: 'Upper East',
    capital: 'Bolgatanga',
    code: 'UPE',
    districts: [
      { name: 'Bolgatanga Municipal', capital: 'Bolgatanga' },
      { name: 'Bawku Municipal', capital: 'Bawku' },
      { name: 'Bawku West District', capital: 'Zebilla' },
      { name: 'Binduri District', capital: 'Binduri' },
      { name: 'Bolgatanga East District', capital: 'Soe' },
      { name: 'Bongo District', capital: 'Bongo' },
      { name: 'Builsa North Municipal', capital: 'Sandema' },
      { name: 'Builsa South District', capital: 'Fumbisi' },
      { name: 'Garu District', capital: 'Garu' },
      { name: 'Kassena-Nankana East Municipal', capital: 'Navrongo' },
      { name: 'Kassena-Nankana West District', capital: 'Paga' },
      { name: 'Nabdam District', capital: 'Nangodi' },
      { name: 'Pusiga District', capital: 'Pusiga' },
      { name: 'Talensi District', capital: 'Tongo' },
      { name: 'Tempane District', capital: 'Tempane' },
    ],
  },
  {
    name: 'Upper West',
    capital: 'Wa',
    code: 'UPW',
    districts: [
      { name: 'Wa Municipal', capital: 'Wa' },
      { name: 'Daffiama-Bussie-Issa District', capital: 'Daffiama' },
      { name: 'Jirapa Municipal', capital: 'Jirapa' },
      { name: 'Lambussie-Karni District', capital: 'Lambussie' },
      { name: 'Lawra Municipal', capital: 'Lawra' },
      { name: 'Nadowli-Kaleo District', capital: 'Nadowli' },
      { name: 'Nandom Municipal', capital: 'Nandom' },
      { name: 'Sissala East Municipal', capital: 'Tumu' },
      { name: 'Sissala West District', capital: 'Gwollu' },
      { name: 'Wa East District', capital: 'Funsi' },
      { name: 'Wa West District', capital: 'Wechiau' },
    ],
  },
];

// ─── Helper functions ──────────────────────────────────────────────────────────

/** All region names as a flat string array */
export const REGION_NAMES = GHANA_REGIONS.map(r => r.name);

/** Get all districts for a given region name */
export function getDistricts(regionName: string): District[] {
  return GHANA_REGIONS.find(r => r.name === regionName)?.districts ?? [];
}

/** Get district names for a given region */
export function getDistrictNames(regionName: string): string[] {
  return getDistricts(regionName).map(d => d.name);
}

/** Flat list of all districts across all regions */
export const ALL_DISTRICTS = GHANA_REGIONS.flatMap(r =>
  r.districts.map(d => ({ ...d, region: r.name, regionCode: r.code }))
);

/** Total district count */
export const TOTAL_DISTRICTS = ALL_DISTRICTS.length;
